project:
  type: website

website:
  title: "RFF Data Governance Guidance"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Version Control"
        contents:
          - docs/version-control/vc1.md
          - docs/version-control/vc2.md
      - section: "Software"
        contents:
          - docs/software/software1.md
      - section: "Data Management"
        contents:
          - docs/data-management/sensitive-data.md

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



