project:
  type: book

book:
  title: "Data Guidance for Researchers"
  url: "https://alexandra-thompson-dc.github.io/rff-data-gov-guidance/" # makes site links work on your remote site, update this if we change domain
  repo-url: "https://github.com/alexandra-thompson-dc/rff-data-gov-guidance"
  repo-actions: [edit, issue]
  favicon: images/black-logo.svg
  sidebar:
    logo: images/black-logomark-vertical.svg
    title: "Data Guidance for Researchers"
    style: "docked"
    search: true
    background: "#c3e1f9"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/alexandra-thompson-dc/rff-data-gov-guidance
          - text: Report a Bug
            href: https://github.com/alexandra-thompson-dc/rff-data-gov-guidance/issues
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    background: "#c3e1f9"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**NOTE** - this site is still under development!"
    type: primary
    position: below-navbar
  chapters:
    - index.qmd
    - part: docs/data-management/index.qmd
      chapters:
        - docs/data-management/data-storage-organization.qmd
        - docs/data-management/data-quality-preparation.qmd
    - part: docs/software/index.qmd
      chapters:
        - docs/software/sq1.qmd
    - part: docs/version-control/index.qmd
      chapters:
        - docs/version-control/vc1.qmd
format:
  html:
    theme: 
      - journal
      - styles.scss
    toc: true
    toc-expand: 1
    toc-depth: 3
    number-depth: 3


