project:
  type: website

website:
  title: "RFF Data Governance Guidance"
  site-url: "https://alexandra-thompson-dc.github.io/rff-data-gov-guidance/" # makes site links work on your remote site, update this if we change domain
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Version Control"
        contents:
          - docs/version-control/vc1.md
          - docs/version-control/vc2.md
      - section: "Software"
        contents:
          - docs/software/software1.md
      - section: "Data Management"
        contents:
          - section: "Storage and Organization"
            href: docs/data-management/storage-organization/index.md
            contents:
              - docs/data-management/storage-organization/storage-options.md
              - docs/data-management/storage-organization/organization.md
              - docs/data-management/storage-organization/file-formats.md
              - docs/data-management/storage-organization/sensitive-data.md

format:
  html:
    theme: darkly
    css: styles.css
    toc: true


